---
services:
  go-web:
    build:
      context: ./web/
      args:
        - VERSION=${VERSION:-dev}
        - PORT=${PORT:-8888}
        - COLOR=${COLOR:-000000}
    image: go-web:${VERSION:-dev}
    container_name: go-web
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    environment:
      - PORT=${PORT:-8888}
      - COLOR=${COLOR:-000000}

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      args:
        - SERVICE=${SERVICE:-go-web}
        - PORT=${PORT:-8888}
        - VERSION=${VERSION:-dev}
    image: nginx-proxy:${VERSION:-dev}
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - go-web
